-- Governance tables for duty scheduling: publication snapshots, blackout dates, and audit trail.

create table if not exists public.duty_schedule_publications (
  id bigint generated by default as identity primary key,
  semester_id uuid not null references public.semesters(id) on delete cascade,
  published_by uuid references public.profiles(id) on delete set null,
  version integer not null,
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  published_at timestamptz not null default now(),
  unique (semester_id, version)
);

create index if not exists idx_duty_schedule_publications_semester
  on public.duty_schedule_publications (semester_id, version desc);

create table if not exists public.duty_schedule_blackout_dates (
  id bigint generated by default as identity primary key,
  semester_id uuid not null references public.semesters(id) on delete cascade,
  blackout_date date not null,
  reason text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (semester_id, blackout_date)
);

create index if not exists idx_duty_schedule_blackout_dates_semester_date
  on public.duty_schedule_blackout_dates (semester_id, blackout_date);

create table if not exists public.duty_schedule_audit_logs (
  id bigint generated by default as identity primary key,
  semester_id uuid not null references public.semesters(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  target_staffer_id uuid references public.profiles(id) on delete set null,
  request_id uuid references public.duty_schedule_change_requests(id) on delete set null,
  action_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_duty_schedule_audit_logs_semester
  on public.duty_schedule_audit_logs (semester_id, created_at desc);

create index if not exists idx_duty_schedule_audit_logs_target
  on public.duty_schedule_audit_logs (target_staffer_id, created_at desc);

-- Repair path for environments where this table may already exist with
-- request_id typed incorrectly (e.g. bigint from an early draft).
do $$
declare
  request_col_type text;
  has_request_fk boolean;
begin
  if to_regclass('public.duty_schedule_audit_logs') is null then
    return;
  end if;

  select data_type
    into request_col_type
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'duty_schedule_audit_logs'
    and column_name = 'request_id';

  if request_col_type is not null and request_col_type <> 'uuid' then
    alter table public.duty_schedule_audit_logs
      drop constraint if exists duty_schedule_audit_logs_request_id_fkey;

    -- Existing non-uuid values cannot map to request UUIDs, so coerce to null.
    alter table public.duty_schedule_audit_logs
      alter column request_id type uuid using null;
  end if;

  select exists (
    select 1
    from pg_constraint
    where conname = 'duty_schedule_audit_logs_request_id_fkey'
      and conrelid = 'public.duty_schedule_audit_logs'::regclass
  ) into has_request_fk;

  if not has_request_fk then
    alter table public.duty_schedule_audit_logs
      add constraint duty_schedule_audit_logs_request_id_fkey
      foreign key (request_id)
      references public.duty_schedule_change_requests(id)
      on delete set null;
  end if;
end
$$;

alter table public.duty_schedule_publications enable row level security;
alter table public.duty_schedule_blackout_dates enable row level security;
alter table public.duty_schedule_audit_logs enable row level security;

drop policy if exists "Duty publications readable by authenticated users" on public.duty_schedule_publications;
create policy "Duty publications readable by authenticated users"
  on public.duty_schedule_publications
  for select
  using (auth.role() = 'authenticated');

drop policy if exists "Duty publications writable by admins" on public.duty_schedule_publications;
create policy "Duty publications writable by admins"
  on public.duty_schedule_publications
  for all
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'admin'
    )
  );

drop policy if exists "Duty blackout dates readable by authenticated users" on public.duty_schedule_blackout_dates;
create policy "Duty blackout dates readable by authenticated users"
  on public.duty_schedule_blackout_dates
  for select
  using (auth.role() = 'authenticated');

drop policy if exists "Duty blackout dates writable by admins" on public.duty_schedule_blackout_dates;
create policy "Duty blackout dates writable by admins"
  on public.duty_schedule_blackout_dates
  for all
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'admin'
    )
  );

drop policy if exists "Duty audit logs readable by authenticated users" on public.duty_schedule_audit_logs;
create policy "Duty audit logs readable by authenticated users"
  on public.duty_schedule_audit_logs
  for select
  using (auth.role() = 'authenticated');

drop policy if exists "Duty audit logs insert by authenticated actor" on public.duty_schedule_audit_logs;
create policy "Duty audit logs insert by authenticated actor"
  on public.duty_schedule_audit_logs
  for insert
  with check (
    auth.role() = 'authenticated'
    and (actor_id is null or actor_id = auth.uid())
  );

create or replace function public.approve_duty_schedule_change_request(
  p_request_id uuid,
  p_reviewer_id uuid default auth.uid()
)
returns table (
  request_id uuid,
  staffer_id uuid,
  semester_id uuid,
  from_day integer,
  to_day integer,
  reviewed_by uuid,
  reviewed_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.duty_schedule_change_requests%rowtype;
  v_schedule_id bigint;
  v_current_day integer;
  v_requested_count integer;
  v_capacity integer;
  v_actor_division text;
  v_source_scribes integer;
  v_source_creatives integer;
  v_source_total integer;
  v_target_scribes integer;
  v_target_creatives integer;
  v_target_total integer;
  v_reviewer_id uuid;
  v_now timestamptz := now();
  v_scheduling_open boolean;
begin
  v_reviewer_id := coalesce(p_reviewer_id, auth.uid());

  if v_reviewer_id is null then
    raise exception 'Reviewer identity is required';
  end if;

  if not exists (
    select 1
    from public.profiles p
    where p.id = v_reviewer_id
      and p.role = 'admin'
  ) then
    raise exception 'Only admins can approve duty schedule change requests';
  end if;

  select *
    into v_request
  from public.duty_schedule_change_requests r
  where r.id = p_request_id
  for update;

  if not found then
    raise exception 'Duty schedule change request not found';
  end if;

  if v_request.status <> 'pending' then
    raise exception 'Only pending requests can be approved';
  end if;

  if v_request.current_duty_day = v_request.requested_duty_day then
    raise exception 'Requested day is the same as current duty day';
  end if;

  select s.scheduling_open,
         case v_request.requested_duty_day
           when 0 then coalesce(s.monday_slots, 10)
           when 1 then coalesce(s.tuesday_slots, 10)
           when 2 then coalesce(s.wednesday_slots, 10)
           when 3 then coalesce(s.thursday_slots, 10)
           when 4 then coalesce(s.friday_slots, 10)
           else 10
         end
    into v_scheduling_open, v_capacity
  from public.semesters s
  where s.id = v_request.semester_id;

  if coalesce(v_scheduling_open, false) = false then
    raise exception 'Scheduling is closed for this semester';
  end if;

  select ds.id, ds.duty_day
    into v_schedule_id, v_current_day
  from public.duty_schedules ds
  where ds.semester_id = v_request.semester_id
    and ds.staffer_id = v_request.staffer_id
  for update;

  if v_schedule_id is null then
    raise exception 'Staff member does not have an existing duty schedule';
  end if;

  if v_current_day <> v_request.current_duty_day then
    raise exception 'Request is stale because the current duty day already changed';
  end if;

  select count(*)
    into v_requested_count
  from public.duty_schedules ds
  where ds.semester_id = v_request.semester_id
    and ds.duty_day = v_request.requested_duty_day
    and ds.staffer_id <> v_request.staffer_id;

  if v_requested_count + 1 > coalesce(v_capacity, 10) then
    raise exception 'Requested day is already full (%/%).', v_requested_count, coalesce(v_capacity, 10);
  end if;

  select case
           when lower(trim(coalesce(p.division, ''))) in ('scribe', 'scribes') then 'Scribes'
           when lower(trim(coalesce(p.division, ''))) in ('creative', 'creatives') then 'Creatives'
           else null
         end
    into v_actor_division
  from public.profiles p
  where p.id = v_request.staffer_id;

  if v_actor_division in ('Scribes', 'Creatives') then
    select
      count(*) filter (where lower(trim(coalesce(p.division, ''))) in ('scribe', 'scribes')),
      count(*) filter (where lower(trim(coalesce(p.division, ''))) in ('creative', 'creatives')),
      count(*)
      into v_source_scribes, v_source_creatives, v_source_total
    from public.duty_schedules ds
    join public.profiles p on p.id = ds.staffer_id
    where ds.semester_id = v_request.semester_id
      and ds.duty_day = v_request.current_duty_day
      and ds.staffer_id <> v_request.staffer_id;

    select
      count(*) filter (where lower(trim(coalesce(p.division, ''))) in ('scribe', 'scribes')),
      count(*) filter (where lower(trim(coalesce(p.division, ''))) in ('creative', 'creatives')),
      count(*)
      into v_target_scribes, v_target_creatives, v_target_total
    from public.duty_schedules ds
    join public.profiles p on p.id = ds.staffer_id
    where ds.semester_id = v_request.semester_id
      and ds.duty_day = v_request.requested_duty_day
      and ds.staffer_id <> v_request.staffer_id;

    if v_actor_division = 'Scribes' then
      v_target_scribes := coalesce(v_target_scribes, 0) + 1;
    elsif v_actor_division = 'Creatives' then
      v_target_creatives := coalesce(v_target_creatives, 0) + 1;
    end if;
    v_target_total := coalesce(v_target_total, 0) + 1;

    if coalesce(v_source_total, 0) > 0
      and (coalesce(v_source_scribes, 0) = 0 or coalesce(v_source_creatives, 0) = 0) then
      raise exception 'Balance policy violation: source day must keep both Scribes and Creatives';
    end if;

    if coalesce(v_target_total, 0) > 0
      and (coalesce(v_target_scribes, 0) = 0 or coalesce(v_target_creatives, 0) = 0) then
      raise exception 'Balance policy violation: target day must keep both Scribes and Creatives';
    end if;
  end if;

  update public.duty_schedules ds
    set duty_day = v_request.requested_duty_day
  where ds.id = v_schedule_id;

  update public.duty_schedule_change_requests r
    set status = 'approved',
        reviewed_at = v_now,
        reviewed_by = v_reviewer_id,
        review_notes = null
  where r.id = v_request.id;

  insert into public.duty_schedule_audit_logs (
    semester_id,
    actor_id,
    target_staffer_id,
    request_id,
    action_type,
    metadata
  ) values (
    v_request.semester_id,
    v_reviewer_id,
    v_request.staffer_id,
    v_request.id,
    'duty_change_approved',
    jsonb_build_object(
      'from_day', v_request.current_duty_day,
      'to_day', v_request.requested_duty_day,
      'enforced_by', 'approve_duty_schedule_change_request'
    )
  );

  return query
  select
    v_request.id,
    v_request.staffer_id,
    v_request.semester_id,
    v_request.current_duty_day,
    v_request.requested_duty_day,
    v_reviewer_id,
    v_now;
end;
$$;

grant execute on function public.approve_duty_schedule_change_request(uuid, uuid) to authenticated;
